// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNTapodFLPrssau-uPMDlE802EBdHxek',
    appId: '1:942884544662:web:c5e010162876fc2d9b62b7',
    messagingSenderId: '942884544662',
    projectId: 'chatapptutorial-c095b',
    authDomain: 'chatapptutorial-c095b.firebaseapp.com',
    storageBucket: 'chatapptutorial-c095b.appspot.com',
    measurementId: 'G-5M1GC30B1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1XkKRUqZ2PBY0jevO58xm_RVbhHOosY',
    appId: '1:942884544662:android:91ed55427eb8e9ff9b62b7',
    messagingSenderId: '942884544662',
    projectId: 'chatapptutorial-c095b',
    storageBucket: 'chatapptutorial-c095b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9VyWq5U57asx7-HdRYXEY-eOVbCOxiDo',
    appId: '1:942884544662:ios:b516fd747489f7b19b62b7',
    messagingSenderId: '942884544662',
    projectId: 'chatapptutorial-c095b',
    storageBucket: 'chatapptutorial-c095b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9VyWq5U57asx7-HdRYXEY-eOVbCOxiDo',
    appId: '1:942884544662:ios:b516fd747489f7b19b62b7',
    messagingSenderId: '942884544662',
    projectId: 'chatapptutorial-c095b',
    storageBucket: 'chatapptutorial-c095b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgNTapodFLPrssau-uPMDlE802EBdHxek',
    appId: '1:942884544662:web:41fabd18c669f1c89b62b7',
    messagingSenderId: '942884544662',
    projectId: 'chatapptutorial-c095b',
    authDomain: 'chatapptutorial-c095b.firebaseapp.com',
    storageBucket: 'chatapptutorial-c095b.appspot.com',
    measurementId: 'G-01ZV8DLW98',
  );
}
